bool initialize
bool analyze_previous
geometry_msgs/Pose2D goal_pose
bool get_pose_only
string controller_name
string proxy_name
string behavior_primitive
---
tabletop_pushing/PushVector push
geometry_msgs/Point centroid
float64 theta
bool no_push
bool no_objects
