bool initialize
bool analyze_previous
geometry_msgs/Pose2D goal_pose
bool learn_start_loc
bool new_object
bool get_pose_only
string controller_name
string proxy_name
string behavior_primitive
string tool_proxy_name
string trial_id
string start_loc_weights_path
int32 num_start_loc_clusters
int32 num_start_loc_sample_locs
int32 num_start_loc_pushes_per_sample
---
tabletop_pushing/PushVector push
geometry_msgs/Point centroid
geometry_msgs/PoseStamped tool_x
geometry_msgs/Pose2D goal_pose
float64 theta
bool no_push
bool no_objects
float64[] shape_descriptor