# To add a new primitive need to put in perform_push() in tabletop_executive.py, need to add which controllers can use it
# need to add a precondiiton method for it

ROBOT_ARMS = ['r', 'l']
# ROBOT_ARMS = ['r']
# ROBOT_ARMS = ['l']
CENTROID_CONTROLLER ='centroid_controller'
TOOL_CENTROID_CONTROLLER ='tool_centroid_controller'
SPIN_COMPENSATION = 'spin_compensation'
SPIN_TO_HEADING = 'spin_to_heading'
DIRECT_GOAL_CONTROLLER = 'direct_goal_controller'
DIRECT_GOAL_GRIPPER_CONTROLLER = 'direct_goal_gripper_controller'
CONTROLLERS = [CENTROID_CONTROLLER, SPIN_COMPENSATION, DIRECT_GOAL_CONTROLLER]
# CONTROLLERS = [SPIN_COMPENSATION]
# CONTROLLERS = [DIRECT_GOAL_CONTROLLER]
# CONTROLLERS = [TOOL_CENTROID_CONTROLLER]

GRIPPER_PUSH = 'gripper_push'
GRIPPER_SWEEP = 'gripper_sweep'
TOOL_SWEEP = 'tool_sweep'
OVERHEAD_PUSH = 'overhead_push'
PINCHER_PUSH = 'pincher_push'
GRIPPER_PULL = 'gripper_pull'
PUSH_PRIMITIVES = [PINCHER_PUSH, OVERHEAD_PUSH, GRIPPER_PUSH, GRIPPER_SWEEP]
# PUSH_PRIMITIVES = [GRIPPER_SWEEP]
TOOL_PRIMITIVES = [TOOL_SWEEP]
BEHAVIOR_PRIMITIVES = {CENTROID_CONTROLLER:PUSH_PRIMITIVES, SPIN_COMPENSATION:PUSH_PRIMITIVES,
                       DIRECT_GOAL_CONTROLLER:[GRIPPER_PULL],
                       DIRECT_GOAL_GRIPPER_CONTROLLER:[GRIPPER_PULL],
                       TOOL_CENTROID_CONTROLLER:TOOL_PRIMITIVES}

ELLIPSE_PROXY = 'ellipse'
CENTROID_PROXY = 'centroid'
SPHERE_PROXY = 'sphere'
CYLINDER_PROXY = 'cylinder'
BOUNDING_BOX_XY_PROXY = 'bounding_box_xy'

HACK_TOOL_PROXY = 'hack'
EE_TOOL_PROXY = 'end_effector_tool'

CENTROID_PROXIES = [CENTROID_PROXY, SPHERE_PROXY, BOUNDING_BOX_XY_PROXY]
# CENTROID_PROXIES = [CENTROID_PROXY]
POSE_PROXIES = [ELLIPSE_PROXY, BOUNDING_BOX_XY_PROXY]

PERCEPTUAL_PROXIES = {CENTROID_CONTROLLER:CENTROID_PROXIES,
                      SPIN_COMPENSATION:POSE_PROXIES,
                      DIRECT_GOAL_CONTROLLER:CENTROID_PROXIES,
                      DIRECT_GOAL_GRIPPER_CONTROLLER:CENTROID_PROXIES,
                      TOOL_CENTROID_CONTROLLER:CENTROID_PROXIES}

CENTROID_PUSH_PRECONDITION = 'centroid_push'
CENTROID_PULL_PRECONDITION = 'centroid_pull'
TOOL_SWEEP_PRECONDITION = 'tool_sweep'
PRECONDITION_METHODS = {GRIPPER_PULL:CENTROID_PULL_PRECONDITION,
                        OVERHEAD_PUSH:CENTROID_PUSH_PRECONDITION,
                        GRIPPER_PUSH:CENTROID_PUSH_PRECONDITION,
                        GRIPPER_SWEEP:CENTROID_PUSH_PRECONDITION,
                        PINCHER_PUSH:CENTROID_PUSH_PRECONDITION,
                        TOOL_SWEEP:TOOL_SWEEP_PRECONDITION}
