# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'joint_iface_gui.ui'
#
# Created: Wed Dec 12 03:14:00 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(652, 988)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame = QtGui.QFrame(Frame)
        self.frame.setGeometry(QtCore.QRect(340, 130, 281, 791))
        self.frame.setStyleSheet(_fromUtf8("image: url(:/resources/ur10_arm.png);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_7 = QtGui.QLabel(Frame)
        self.label_7.setGeometry(QtCore.QRect(180, 20, 301, 41))
        self.label_7.setStyleSheet(_fromUtf8("font: 75 30pt ;"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.widget = QtGui.QWidget(Frame)
        self.widget.setGeometry(QtCore.QRect(41, 81, 261, 101))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setStyleSheet(_fromUtf8("font: 75 16pt ;"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.wrist_3_up = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_3_up.sizePolicy().hasHeightForWidth())
        self.wrist_3_up.setSizePolicy(sizePolicy)
        self.wrist_3_up.setBaseSize(QtCore.QSize(80, 80))
        self.wrist_3_up.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_pos_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.wrist_3_up.setText(_fromUtf8(""))
        self.wrist_3_up.setObjectName(_fromUtf8("wrist_3_up"))
        self.horizontalLayout_2.addWidget(self.wrist_3_up)
        self.wrist_3_down = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_3_down.sizePolicy().hasHeightForWidth())
        self.wrist_3_down.setSizePolicy(sizePolicy)
        self.wrist_3_down.setBaseSize(QtCore.QSize(80, 80))
        self.wrist_3_down.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_neg_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.wrist_3_down.setText(_fromUtf8(""))
        self.wrist_3_down.setObjectName(_fromUtf8("wrist_3_down"))
        self.horizontalLayout_2.addWidget(self.wrist_3_down)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.widget1 = QtGui.QWidget(Frame)
        self.widget1.setGeometry(QtCore.QRect(41, 191, 261, 101))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.widget1)
        self.label_4.setStyleSheet(_fromUtf8("font: 75 16pt ;"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.wrist_2_left = QtGui.QPushButton(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_2_left.sizePolicy().hasHeightForWidth())
        self.wrist_2_left.setSizePolicy(sizePolicy)
        self.wrist_2_left.setBaseSize(QtCore.QSize(80, 80))
        self.wrist_2_left.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_z_neg_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.wrist_2_left.setText(_fromUtf8(""))
        self.wrist_2_left.setObjectName(_fromUtf8("wrist_2_left"))
        self.horizontalLayout_3.addWidget(self.wrist_2_left)
        self.wrist_2_right = QtGui.QPushButton(self.widget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_2_right.sizePolicy().hasHeightForWidth())
        self.wrist_2_right.setSizePolicy(sizePolicy)
        self.wrist_2_right.setBaseSize(QtCore.QSize(80, 80))
        self.wrist_2_right.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_z_pos_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.wrist_2_right.setText(_fromUtf8(""))
        self.wrist_2_right.setObjectName(_fromUtf8("wrist_2_right"))
        self.horizontalLayout_3.addWidget(self.wrist_2_right)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.widget2 = QtGui.QWidget(Frame)
        self.widget2.setGeometry(QtCore.QRect(41, 301, 261, 101))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_5 = QtGui.QLabel(self.widget2)
        self.label_5.setStyleSheet(_fromUtf8("font: 75 16pt ;"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.wrist_1_up = QtGui.QPushButton(self.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_1_up.sizePolicy().hasHeightForWidth())
        self.wrist_1_up.setSizePolicy(sizePolicy)
        self.wrist_1_up.setBaseSize(QtCore.QSize(80, 80))
        self.wrist_1_up.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_pos_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.wrist_1_up.setText(_fromUtf8(""))
        self.wrist_1_up.setObjectName(_fromUtf8("wrist_1_up"))
        self.horizontalLayout_4.addWidget(self.wrist_1_up)
        self.wrist_1_down = QtGui.QPushButton(self.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_1_down.sizePolicy().hasHeightForWidth())
        self.wrist_1_down.setSizePolicy(sizePolicy)
        self.wrist_1_down.setBaseSize(QtCore.QSize(80, 80))
        self.wrist_1_down.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_neg_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.wrist_1_down.setText(_fromUtf8(""))
        self.wrist_1_down.setObjectName(_fromUtf8("wrist_1_down"))
        self.horizontalLayout_4.addWidget(self.wrist_1_down)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.widget3 = QtGui.QWidget(Frame)
        self.widget3.setGeometry(QtCore.QRect(41, 491, 261, 111))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_6 = QtGui.QLabel(self.widget3)
        self.label_6.setStyleSheet(_fromUtf8("font: 75 16pt ;"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.elbow_up = QtGui.QPushButton(self.widget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elbow_up.sizePolicy().hasHeightForWidth())
        self.elbow_up.setSizePolicy(sizePolicy)
        self.elbow_up.setBaseSize(QtCore.QSize(80, 80))
        self.elbow_up.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_pos_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.elbow_up.setText(_fromUtf8(""))
        self.elbow_up.setObjectName(_fromUtf8("elbow_up"))
        self.horizontalLayout_5.addWidget(self.elbow_up)
        self.elbow_down = QtGui.QPushButton(self.widget3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elbow_down.sizePolicy().hasHeightForWidth())
        self.elbow_down.setSizePolicy(sizePolicy)
        self.elbow_down.setBaseSize(QtCore.QSize(80, 80))
        self.elbow_down.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_neg_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.elbow_down.setText(_fromUtf8(""))
        self.elbow_down.setObjectName(_fromUtf8("elbow_down"))
        self.horizontalLayout_5.addWidget(self.elbow_down)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.widget4 = QtGui.QWidget(Frame)
        self.widget4.setGeometry(QtCore.QRect(41, 721, 261, 111))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget4)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget4)
        self.label_2.setStyleSheet(_fromUtf8("font: 75 16pt ;"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.shoulder_lift_up = QtGui.QPushButton(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_lift_up.sizePolicy().hasHeightForWidth())
        self.shoulder_lift_up.setSizePolicy(sizePolicy)
        self.shoulder_lift_up.setBaseSize(QtCore.QSize(80, 80))
        self.shoulder_lift_up.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_pos_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.shoulder_lift_up.setText(_fromUtf8(""))
        self.shoulder_lift_up.setObjectName(_fromUtf8("shoulder_lift_up"))
        self.horizontalLayout_6.addWidget(self.shoulder_lift_up)
        self.shoulder_lift_down = QtGui.QPushButton(self.widget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_lift_down.sizePolicy().hasHeightForWidth())
        self.shoulder_lift_down.setSizePolicy(sizePolicy)
        self.shoulder_lift_down.setBaseSize(QtCore.QSize(80, 80))
        self.shoulder_lift_down.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_neg_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.shoulder_lift_down.setText(_fromUtf8(""))
        self.shoulder_lift_down.setObjectName(_fromUtf8("shoulder_lift_down"))
        self.horizontalLayout_6.addWidget(self.shoulder_lift_down)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.widget5 = QtGui.QWidget(Frame)
        self.widget5.setGeometry(QtCore.QRect(41, 841, 261, 111))
        self.widget5.setObjectName(_fromUtf8("widget5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget5)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.widget5)
        self.label.setStyleSheet(_fromUtf8("font: 75 16pt ;"))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.shoulder_pan_left = QtGui.QPushButton(self.widget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_pan_left.sizePolicy().hasHeightForWidth())
        self.shoulder_pan_left.setSizePolicy(sizePolicy)
        self.shoulder_pan_left.setBaseSize(QtCore.QSize(80, 80))
        self.shoulder_pan_left.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_z_neg_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.shoulder_pan_left.setText(_fromUtf8(""))
        self.shoulder_pan_left.setObjectName(_fromUtf8("shoulder_pan_left"))
        self.horizontalLayout_7.addWidget(self.shoulder_pan_left)
        self.shoulder_pan_right = QtGui.QPushButton(self.widget5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_pan_right.sizePolicy().hasHeightForWidth())
        self.shoulder_pan_right.setSizePolicy(sizePolicy)
        self.shoulder_pan_right.setBaseSize(QtCore.QSize(80, 80))
        self.shoulder_pan_right.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_z_pos_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.shoulder_pan_right.setText(_fromUtf8(""))
        self.shoulder_pan_right.setObjectName(_fromUtf8("shoulder_pan_right"))
        self.horizontalLayout_7.addWidget(self.shoulder_pan_right)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", "Joint Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Wrist 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "Wrist 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Wrist 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "Elbow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Shoulder Lift", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Shoulder Pan", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
