# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'joint_iface_gui.ui'
#
# Created: Fri Mar  8 22:25:49 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName(_fromUtf8("Frame"))
        Frame.resize(495, 712)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_7 = QtGui.QLabel(Frame)
        self.label_7.setStyleSheet(_fromUtf8("font: 75 24pt ;"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_2.addWidget(self.label_7)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_12 = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setStyleSheet(_fromUtf8("font: 75 16pt ;"))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_12.addWidget(self.label_12)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.shoulder_pan_left = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_pan_left.sizePolicy().hasHeightForWidth())
        self.shoulder_pan_left.setSizePolicy(sizePolicy)
        self.shoulder_pan_left.setBaseSize(QtCore.QSize(80, 80))
        self.shoulder_pan_left.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_z_neg_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.shoulder_pan_left.setText(_fromUtf8(""))
        self.shoulder_pan_left.setObjectName(_fromUtf8("shoulder_pan_left"))
        self.horizontalLayout_28.addWidget(self.shoulder_pan_left)
        self.shoulder_pan_right = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_pan_right.sizePolicy().hasHeightForWidth())
        self.shoulder_pan_right.setSizePolicy(sizePolicy)
        self.shoulder_pan_right.setBaseSize(QtCore.QSize(80, 80))
        self.shoulder_pan_right.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_z_pos_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.shoulder_pan_right.setText(_fromUtf8(""))
        self.shoulder_pan_right.setObjectName(_fromUtf8("shoulder_pan_right"))
        self.horizontalLayout_28.addWidget(self.shoulder_pan_right)
        self.verticalLayout_12.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_27.addLayout(self.verticalLayout_12)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.label = QtGui.QLabel(Frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_17.addWidget(self.label)
        self.shoulder_pan_vel = QtGui.QDoubleSpinBox(Frame)
        self.shoulder_pan_vel.setMaximum(1.0)
        self.shoulder_pan_vel.setSingleStep(0.05)
        self.shoulder_pan_vel.setProperty("value", 0.1)
        self.shoulder_pan_vel.setObjectName(_fromUtf8("shoulder_pan_vel"))
        self.verticalLayout_17.addWidget(self.shoulder_pan_vel)
        self.horizontalLayout_29.addLayout(self.verticalLayout_17)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_29)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem)
        self.shoulder_pan_num = QtGui.QTextBrowser(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_pan_num.sizePolicy().hasHeightForWidth())
        self.shoulder_pan_num.setSizePolicy(sizePolicy)
        self.shoulder_pan_num.setMinimumSize(QtCore.QSize(80, 41))
        self.shoulder_pan_num.setMaximumSize(QtCore.QSize(120, 41))
        self.shoulder_pan_num.setBaseSize(QtCore.QSize(100, 41))
        self.shoulder_pan_num.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.shoulder_pan_num.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.shoulder_pan_num.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.shoulder_pan_num.setObjectName(_fromUtf8("shoulder_pan_num"))
        self.horizontalLayout_31.addWidget(self.shoulder_pan_num)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem1)
        self.verticalLayout_14.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.shoulder_pan_prog_neg = QtGui.QProgressBar(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_pan_prog_neg.sizePolicy().hasHeightForWidth())
        self.shoulder_pan_prog_neg.setSizePolicy(sizePolicy)
        self.shoulder_pan_prog_neg.setMaximumSize(QtCore.QSize(16777215, 41))
        self.shoulder_pan_prog_neg.setMinimum(0)
        self.shoulder_pan_prog_neg.setProperty("value", 0)
        self.shoulder_pan_prog_neg.setInvertedAppearance(True)
        self.shoulder_pan_prog_neg.setFormat(_fromUtf8(""))
        self.shoulder_pan_prog_neg.setObjectName(_fromUtf8("shoulder_pan_prog_neg"))
        self.horizontalLayout_30.addWidget(self.shoulder_pan_prog_neg)
        self.shoulder_pan_prog_pos = QtGui.QProgressBar(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_pan_prog_pos.sizePolicy().hasHeightForWidth())
        self.shoulder_pan_prog_pos.setSizePolicy(sizePolicy)
        self.shoulder_pan_prog_pos.setMaximumSize(QtCore.QSize(16777215, 41))
        self.shoulder_pan_prog_pos.setMinimum(0)
        self.shoulder_pan_prog_pos.setProperty("value", 0)
        self.shoulder_pan_prog_pos.setInvertedAppearance(False)
        self.shoulder_pan_prog_pos.setFormat(_fromUtf8(""))
        self.shoulder_pan_prog_pos.setObjectName(_fromUtf8("shoulder_pan_prog_pos"))
        self.horizontalLayout_30.addWidget(self.shoulder_pan_prog_pos)
        self.verticalLayout_14.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_27.addLayout(self.verticalLayout_14)
        self.verticalLayout_2.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_6 = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet(_fromUtf8("font: 75 16pt ;"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.shoulder_lift_up = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_lift_up.sizePolicy().hasHeightForWidth())
        self.shoulder_lift_up.setSizePolicy(sizePolicy)
        self.shoulder_lift_up.setBaseSize(QtCore.QSize(80, 80))
        self.shoulder_lift_up.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_pos_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.shoulder_lift_up.setText(_fromUtf8(""))
        self.shoulder_lift_up.setObjectName(_fromUtf8("shoulder_lift_up"))
        self.horizontalLayout_5.addWidget(self.shoulder_lift_up)
        self.shoulder_lift_down = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_lift_down.sizePolicy().hasHeightForWidth())
        self.shoulder_lift_down.setSizePolicy(sizePolicy)
        self.shoulder_lift_down.setBaseSize(QtCore.QSize(80, 80))
        self.shoulder_lift_down.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_neg_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.shoulder_lift_down.setText(_fromUtf8(""))
        self.shoulder_lift_down.setObjectName(_fromUtf8("shoulder_lift_down"))
        self.horizontalLayout_5.addWidget(self.shoulder_lift_down)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_23.addLayout(self.verticalLayout_6)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.label_2 = QtGui.QLabel(Frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_16.addWidget(self.label_2)
        self.shoulder_lift_vel = QtGui.QDoubleSpinBox(Frame)
        self.shoulder_lift_vel.setMaximum(1.0)
        self.shoulder_lift_vel.setSingleStep(0.05)
        self.shoulder_lift_vel.setProperty("value", 0.1)
        self.shoulder_lift_vel.setObjectName(_fromUtf8("shoulder_lift_vel"))
        self.verticalLayout_16.addWidget(self.shoulder_lift_vel)
        self.horizontalLayout_24.addLayout(self.verticalLayout_16)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_24)
        self.verticalLayout_24 = QtGui.QVBoxLayout()
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName(_fromUtf8("horizontalLayout_32"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem2)
        self.shoulder_lift_num = QtGui.QTextBrowser(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_lift_num.sizePolicy().hasHeightForWidth())
        self.shoulder_lift_num.setSizePolicy(sizePolicy)
        self.shoulder_lift_num.setMinimumSize(QtCore.QSize(80, 41))
        self.shoulder_lift_num.setMaximumSize(QtCore.QSize(120, 41))
        self.shoulder_lift_num.setBaseSize(QtCore.QSize(100, 41))
        self.shoulder_lift_num.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.shoulder_lift_num.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.shoulder_lift_num.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.shoulder_lift_num.setObjectName(_fromUtf8("shoulder_lift_num"))
        self.horizontalLayout_32.addWidget(self.shoulder_lift_num)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem3)
        self.verticalLayout_24.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        self.shoulder_lift_prog_neg = QtGui.QProgressBar(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_lift_prog_neg.sizePolicy().hasHeightForWidth())
        self.shoulder_lift_prog_neg.setSizePolicy(sizePolicy)
        self.shoulder_lift_prog_neg.setMaximumSize(QtCore.QSize(16777215, 41))
        self.shoulder_lift_prog_neg.setMinimum(0)
        self.shoulder_lift_prog_neg.setProperty("value", 0)
        self.shoulder_lift_prog_neg.setInvertedAppearance(True)
        self.shoulder_lift_prog_neg.setFormat(_fromUtf8(""))
        self.shoulder_lift_prog_neg.setObjectName(_fromUtf8("shoulder_lift_prog_neg"))
        self.horizontalLayout_33.addWidget(self.shoulder_lift_prog_neg)
        self.shoulder_lift_prog_pos = QtGui.QProgressBar(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shoulder_lift_prog_pos.sizePolicy().hasHeightForWidth())
        self.shoulder_lift_prog_pos.setSizePolicy(sizePolicy)
        self.shoulder_lift_prog_pos.setMaximumSize(QtCore.QSize(16777215, 41))
        self.shoulder_lift_prog_pos.setMinimum(0)
        self.shoulder_lift_prog_pos.setProperty("value", 0)
        self.shoulder_lift_prog_pos.setInvertedAppearance(False)
        self.shoulder_lift_prog_pos.setFormat(_fromUtf8(""))
        self.shoulder_lift_prog_pos.setObjectName(_fromUtf8("shoulder_lift_prog_pos"))
        self.horizontalLayout_33.addWidget(self.shoulder_lift_prog_pos)
        self.verticalLayout_24.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_23.addLayout(self.verticalLayout_24)
        self.verticalLayout_2.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_5 = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet(_fromUtf8("font: 75 16pt ;"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.elbow_up = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elbow_up.sizePolicy().hasHeightForWidth())
        self.elbow_up.setSizePolicy(sizePolicy)
        self.elbow_up.setBaseSize(QtCore.QSize(80, 80))
        self.elbow_up.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_pos_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.elbow_up.setText(_fromUtf8(""))
        self.elbow_up.setObjectName(_fromUtf8("elbow_up"))
        self.horizontalLayout_4.addWidget(self.elbow_up)
        self.elbow_down = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elbow_down.sizePolicy().hasHeightForWidth())
        self.elbow_down.setSizePolicy(sizePolicy)
        self.elbow_down.setBaseSize(QtCore.QSize(80, 80))
        self.elbow_down.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_neg_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.elbow_down.setText(_fromUtf8(""))
        self.elbow_down.setObjectName(_fromUtf8("elbow_down"))
        self.horizontalLayout_4.addWidget(self.elbow_down)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_21.addLayout(self.verticalLayout_5)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_22.addLayout(self.verticalLayout_15)
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.label_15 = QtGui.QLabel(Frame)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_20.addWidget(self.label_15)
        self.elbow_vel = QtGui.QDoubleSpinBox(Frame)
        self.elbow_vel.setMaximum(1.0)
        self.elbow_vel.setSingleStep(0.05)
        self.elbow_vel.setProperty("value", 0.1)
        self.elbow_vel.setObjectName(_fromUtf8("elbow_vel"))
        self.verticalLayout_20.addWidget(self.elbow_vel)
        self.horizontalLayout_22.addLayout(self.verticalLayout_20)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_22)
        self.verticalLayout_25 = QtGui.QVBoxLayout()
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem4)
        self.elbow_num = QtGui.QTextBrowser(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elbow_num.sizePolicy().hasHeightForWidth())
        self.elbow_num.setSizePolicy(sizePolicy)
        self.elbow_num.setMinimumSize(QtCore.QSize(80, 41))
        self.elbow_num.setMaximumSize(QtCore.QSize(120, 41))
        self.elbow_num.setBaseSize(QtCore.QSize(100, 41))
        self.elbow_num.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.elbow_num.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.elbow_num.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.elbow_num.setObjectName(_fromUtf8("elbow_num"))
        self.horizontalLayout_34.addWidget(self.elbow_num)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem5)
        self.verticalLayout_25.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        self.elbow_prog_neg = QtGui.QProgressBar(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elbow_prog_neg.sizePolicy().hasHeightForWidth())
        self.elbow_prog_neg.setSizePolicy(sizePolicy)
        self.elbow_prog_neg.setMaximumSize(QtCore.QSize(16777215, 41))
        self.elbow_prog_neg.setMinimum(0)
        self.elbow_prog_neg.setProperty("value", 0)
        self.elbow_prog_neg.setInvertedAppearance(True)
        self.elbow_prog_neg.setFormat(_fromUtf8(""))
        self.elbow_prog_neg.setObjectName(_fromUtf8("elbow_prog_neg"))
        self.horizontalLayout_35.addWidget(self.elbow_prog_neg)
        self.elbow_prog_pos = QtGui.QProgressBar(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elbow_prog_pos.sizePolicy().hasHeightForWidth())
        self.elbow_prog_pos.setSizePolicy(sizePolicy)
        self.elbow_prog_pos.setMaximumSize(QtCore.QSize(16777215, 41))
        self.elbow_prog_pos.setMinimum(0)
        self.elbow_prog_pos.setProperty("value", 0)
        self.elbow_prog_pos.setInvertedAppearance(False)
        self.elbow_prog_pos.setFormat(_fromUtf8(""))
        self.elbow_prog_pos.setObjectName(_fromUtf8("elbow_prog_pos"))
        self.horizontalLayout_35.addWidget(self.elbow_prog_pos)
        self.verticalLayout_25.addLayout(self.horizontalLayout_35)
        self.horizontalLayout_21.addLayout(self.verticalLayout_25)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setStyleSheet(_fromUtf8("font: 75 16pt ;"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.wrist_1_up = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_1_up.sizePolicy().hasHeightForWidth())
        self.wrist_1_up.setSizePolicy(sizePolicy)
        self.wrist_1_up.setBaseSize(QtCore.QSize(80, 80))
        self.wrist_1_up.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_pos_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.wrist_1_up.setText(_fromUtf8(""))
        self.wrist_1_up.setObjectName(_fromUtf8("wrist_1_up"))
        self.horizontalLayout_3.addWidget(self.wrist_1_up)
        self.wrist_1_down = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_1_down.sizePolicy().hasHeightForWidth())
        self.wrist_1_down.setSizePolicy(sizePolicy)
        self.wrist_1_down.setBaseSize(QtCore.QSize(80, 80))
        self.wrist_1_down.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_neg_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.wrist_1_down.setText(_fromUtf8(""))
        self.wrist_1_down.setObjectName(_fromUtf8("wrist_1_down"))
        self.horizontalLayout_3.addWidget(self.wrist_1_down)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_19.addLayout(self.verticalLayout_4)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.label_16 = QtGui.QLabel(Frame)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_21.addWidget(self.label_16)
        self.wrist_1_vel = QtGui.QDoubleSpinBox(Frame)
        self.wrist_1_vel.setMaximum(1.0)
        self.wrist_1_vel.setSingleStep(0.05)
        self.wrist_1_vel.setProperty("value", 0.1)
        self.wrist_1_vel.setObjectName(_fromUtf8("wrist_1_vel"))
        self.verticalLayout_21.addWidget(self.wrist_1_vel)
        self.horizontalLayout_20.addLayout(self.verticalLayout_21)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_20)
        self.verticalLayout_26 = QtGui.QVBoxLayout()
        self.verticalLayout_26.setObjectName(_fromUtf8("verticalLayout_26"))
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName(_fromUtf8("horizontalLayout_37"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem6)
        self.wrist_1_num = QtGui.QTextBrowser(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_1_num.sizePolicy().hasHeightForWidth())
        self.wrist_1_num.setSizePolicy(sizePolicy)
        self.wrist_1_num.setMinimumSize(QtCore.QSize(80, 41))
        self.wrist_1_num.setMaximumSize(QtCore.QSize(120, 41))
        self.wrist_1_num.setBaseSize(QtCore.QSize(100, 41))
        self.wrist_1_num.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wrist_1_num.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wrist_1_num.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.wrist_1_num.setObjectName(_fromUtf8("wrist_1_num"))
        self.horizontalLayout_37.addWidget(self.wrist_1_num)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem7)
        self.verticalLayout_26.addLayout(self.horizontalLayout_37)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName(_fromUtf8("horizontalLayout_36"))
        self.wrist_1_prog_neg = QtGui.QProgressBar(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_1_prog_neg.sizePolicy().hasHeightForWidth())
        self.wrist_1_prog_neg.setSizePolicy(sizePolicy)
        self.wrist_1_prog_neg.setMaximumSize(QtCore.QSize(16777215, 41))
        self.wrist_1_prog_neg.setMinimum(0)
        self.wrist_1_prog_neg.setProperty("value", 0)
        self.wrist_1_prog_neg.setInvertedAppearance(True)
        self.wrist_1_prog_neg.setFormat(_fromUtf8(""))
        self.wrist_1_prog_neg.setObjectName(_fromUtf8("wrist_1_prog_neg"))
        self.horizontalLayout_36.addWidget(self.wrist_1_prog_neg)
        self.wrist_1_prog_pos = QtGui.QProgressBar(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_1_prog_pos.sizePolicy().hasHeightForWidth())
        self.wrist_1_prog_pos.setSizePolicy(sizePolicy)
        self.wrist_1_prog_pos.setMaximumSize(QtCore.QSize(16777215, 41))
        self.wrist_1_prog_pos.setMinimum(0)
        self.wrist_1_prog_pos.setProperty("value", 0)
        self.wrist_1_prog_pos.setInvertedAppearance(False)
        self.wrist_1_prog_pos.setFormat(_fromUtf8(""))
        self.wrist_1_prog_pos.setObjectName(_fromUtf8("wrist_1_prog_pos"))
        self.horizontalLayout_36.addWidget(self.wrist_1_prog_pos)
        self.verticalLayout_26.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_19.addLayout(self.verticalLayout_26)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_10 = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setStyleSheet(_fromUtf8("font: 75 16pt ;"))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_10.addWidget(self.label_10)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.wrist_2_left = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_2_left.sizePolicy().hasHeightForWidth())
        self.wrist_2_left.setSizePolicy(sizePolicy)
        self.wrist_2_left.setBaseSize(QtCore.QSize(80, 80))
        self.wrist_2_left.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_z_neg_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.wrist_2_left.setText(_fromUtf8(""))
        self.wrist_2_left.setObjectName(_fromUtf8("wrist_2_left"))
        self.horizontalLayout_17.addWidget(self.wrist_2_left)
        self.wrist_2_right = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_2_right.sizePolicy().hasHeightForWidth())
        self.wrist_2_right.setSizePolicy(sizePolicy)
        self.wrist_2_right.setBaseSize(QtCore.QSize(80, 80))
        self.wrist_2_right.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_z_pos_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.wrist_2_right.setText(_fromUtf8(""))
        self.wrist_2_right.setObjectName(_fromUtf8("wrist_2_right"))
        self.horizontalLayout_17.addWidget(self.wrist_2_right)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_16.addLayout(self.verticalLayout_10)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_18.addLayout(self.verticalLayout_13)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.label_17 = QtGui.QLabel(Frame)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_22.addWidget(self.label_17)
        self.wrist_2_vel = QtGui.QDoubleSpinBox(Frame)
        self.wrist_2_vel.setMaximum(1.0)
        self.wrist_2_vel.setSingleStep(0.05)
        self.wrist_2_vel.setProperty("value", 0.1)
        self.wrist_2_vel.setObjectName(_fromUtf8("wrist_2_vel"))
        self.verticalLayout_22.addWidget(self.wrist_2_vel)
        self.horizontalLayout_18.addLayout(self.verticalLayout_22)
        self.horizontalLayout_16.addLayout(self.horizontalLayout_18)
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName(_fromUtf8("verticalLayout_27"))
        self.horizontalLayout_38 = QtGui.QHBoxLayout()
        self.horizontalLayout_38.setObjectName(_fromUtf8("horizontalLayout_38"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem8)
        self.wrist_2_num = QtGui.QTextBrowser(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_2_num.sizePolicy().hasHeightForWidth())
        self.wrist_2_num.setSizePolicy(sizePolicy)
        self.wrist_2_num.setMinimumSize(QtCore.QSize(80, 41))
        self.wrist_2_num.setMaximumSize(QtCore.QSize(120, 41))
        self.wrist_2_num.setBaseSize(QtCore.QSize(100, 41))
        self.wrist_2_num.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wrist_2_num.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wrist_2_num.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.wrist_2_num.setObjectName(_fromUtf8("wrist_2_num"))
        self.horizontalLayout_38.addWidget(self.wrist_2_num)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_38.addItem(spacerItem9)
        self.verticalLayout_27.addLayout(self.horizontalLayout_38)
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName(_fromUtf8("horizontalLayout_39"))
        self.wrist_2_prog_neg = QtGui.QProgressBar(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_2_prog_neg.sizePolicy().hasHeightForWidth())
        self.wrist_2_prog_neg.setSizePolicy(sizePolicy)
        self.wrist_2_prog_neg.setMaximumSize(QtCore.QSize(16777215, 41))
        self.wrist_2_prog_neg.setMinimum(0)
        self.wrist_2_prog_neg.setProperty("value", 0)
        self.wrist_2_prog_neg.setInvertedAppearance(True)
        self.wrist_2_prog_neg.setFormat(_fromUtf8(""))
        self.wrist_2_prog_neg.setObjectName(_fromUtf8("wrist_2_prog_neg"))
        self.horizontalLayout_39.addWidget(self.wrist_2_prog_neg)
        self.wrist_2_prog_pos = QtGui.QProgressBar(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_2_prog_pos.sizePolicy().hasHeightForWidth())
        self.wrist_2_prog_pos.setSizePolicy(sizePolicy)
        self.wrist_2_prog_pos.setMaximumSize(QtCore.QSize(16777215, 41))
        self.wrist_2_prog_pos.setMinimum(0)
        self.wrist_2_prog_pos.setProperty("value", 0)
        self.wrist_2_prog_pos.setInvertedAppearance(False)
        self.wrist_2_prog_pos.setFormat(_fromUtf8(""))
        self.wrist_2_prog_pos.setObjectName(_fromUtf8("wrist_2_prog_pos"))
        self.horizontalLayout_39.addWidget(self.wrist_2_prog_pos)
        self.verticalLayout_27.addLayout(self.horizontalLayout_39)
        self.horizontalLayout_16.addLayout(self.verticalLayout_27)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setStyleSheet(_fromUtf8("font: 75 16pt ;"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.wrist_3_up = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_3_up.sizePolicy().hasHeightForWidth())
        self.wrist_3_up.setSizePolicy(sizePolicy)
        self.wrist_3_up.setBaseSize(QtCore.QSize(80, 80))
        self.wrist_3_up.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_pos_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.wrist_3_up.setText(_fromUtf8(""))
        self.wrist_3_up.setObjectName(_fromUtf8("wrist_3_up"))
        self.horizontalLayout_2.addWidget(self.wrist_3_up)
        self.wrist_3_down = QtGui.QPushButton(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_3_down.sizePolicy().hasHeightForWidth())
        self.wrist_3_down.setSizePolicy(sizePolicy)
        self.wrist_3_down.setBaseSize(QtCore.QSize(80, 80))
        self.wrist_3_down.setStyleSheet(_fromUtf8("image: url(:/resources/rotate_y_neg_on.png);\n"
"background-image: url(:/resources/empty.png);"))
        self.wrist_3_down.setText(_fromUtf8(""))
        self.wrist_3_down.setObjectName(_fromUtf8("wrist_3_down"))
        self.horizontalLayout_2.addWidget(self.wrist_3_down)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_8.addLayout(self.verticalLayout)
        self.verticalLayout_23 = QtGui.QVBoxLayout()
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.label_18 = QtGui.QLabel(Frame)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_23.addWidget(self.label_18)
        self.wrist_3_vel = QtGui.QDoubleSpinBox(Frame)
        self.wrist_3_vel.setMaximum(1.0)
        self.wrist_3_vel.setSingleStep(0.05)
        self.wrist_3_vel.setProperty("value", 0.1)
        self.wrist_3_vel.setObjectName(_fromUtf8("wrist_3_vel"))
        self.verticalLayout_23.addWidget(self.wrist_3_vel)
        self.horizontalLayout_8.addLayout(self.verticalLayout_23)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_28 = QtGui.QVBoxLayout()
        self.verticalLayout_28.setObjectName(_fromUtf8("verticalLayout_28"))
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName(_fromUtf8("horizontalLayout_40"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem10)
        self.wrist_3_num = QtGui.QTextBrowser(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_3_num.sizePolicy().hasHeightForWidth())
        self.wrist_3_num.setSizePolicy(sizePolicy)
        self.wrist_3_num.setMinimumSize(QtCore.QSize(80, 41))
        self.wrist_3_num.setMaximumSize(QtCore.QSize(120, 41))
        self.wrist_3_num.setBaseSize(QtCore.QSize(100, 41))
        self.wrist_3_num.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wrist_3_num.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.wrist_3_num.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.wrist_3_num.setObjectName(_fromUtf8("wrist_3_num"))
        self.horizontalLayout_40.addWidget(self.wrist_3_num)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem11)
        self.verticalLayout_28.addLayout(self.horizontalLayout_40)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName(_fromUtf8("horizontalLayout_41"))
        self.wrist_3_prog_neg = QtGui.QProgressBar(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_3_prog_neg.sizePolicy().hasHeightForWidth())
        self.wrist_3_prog_neg.setSizePolicy(sizePolicy)
        self.wrist_3_prog_neg.setMaximumSize(QtCore.QSize(16777215, 41))
        self.wrist_3_prog_neg.setMinimum(0)
        self.wrist_3_prog_neg.setProperty("value", 0)
        self.wrist_3_prog_neg.setInvertedAppearance(True)
        self.wrist_3_prog_neg.setFormat(_fromUtf8(""))
        self.wrist_3_prog_neg.setObjectName(_fromUtf8("wrist_3_prog_neg"))
        self.horizontalLayout_41.addWidget(self.wrist_3_prog_neg)
        self.wrist_3_prog_pos = QtGui.QProgressBar(Frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wrist_3_prog_pos.sizePolicy().hasHeightForWidth())
        self.wrist_3_prog_pos.setSizePolicy(sizePolicy)
        self.wrist_3_prog_pos.setMaximumSize(QtCore.QSize(16777215, 41))
        self.wrist_3_prog_pos.setMinimum(0)
        self.wrist_3_prog_pos.setProperty("value", 0)
        self.wrist_3_prog_pos.setInvertedAppearance(False)
        self.wrist_3_prog_pos.setFormat(_fromUtf8(""))
        self.wrist_3_prog_pos.setObjectName(_fromUtf8("wrist_3_prog_pos"))
        self.horizontalLayout_41.addWidget(self.wrist_3_prog_pos)
        self.verticalLayout_28.addLayout(self.horizontalLayout_41)
        self.horizontalLayout_9.addLayout(self.verticalLayout_28)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.copy_joint_config = QtGui.QPushButton(Frame)
        self.copy_joint_config.setObjectName(_fromUtf8("copy_joint_config"))
        self.horizontalLayout.addWidget(self.copy_joint_config)
        self.copy_ee_pose = QtGui.QPushButton(Frame)
        self.copy_ee_pose.setObjectName(_fromUtf8("copy_ee_pose"))
        self.horizontalLayout.addWidget(self.copy_ee_pose)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Frame", "Joint Controller", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Frame", "Shoulder Pan", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.shoulder_pan_num.setHtml(QtGui.QApplication.translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">0.36534343</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "Shoulder Lift", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.shoulder_lift_num.setHtml(QtGui.QApplication.translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">0.36534343</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Elbow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Frame", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.elbow_num.setHtml(QtGui.QApplication.translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">0.36534343</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "Wrist 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Frame", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.wrist_1_num.setHtml(QtGui.QApplication.translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">0.36534343</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Frame", "Wrist 2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Frame", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.wrist_2_num.setHtml(QtGui.QApplication.translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">0.36534343</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Wrist 3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Frame", "Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.wrist_3_num.setHtml(QtGui.QApplication.translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">0.36534343</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.copy_joint_config.setText(QtGui.QApplication.translate("Frame", "Copy Joint Config", None, QtGui.QApplication.UnicodeUTF8))
        self.copy_ee_pose.setText(QtGui.QApplication.translate("Frame", "Copy EE Pose", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
