<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

<include filename="$(find ur10_description)/urdf/arm.transmission.xacro" />

<!--
DH for UR5:
a = [0.00000, -0.42500, -0.39225,  0.00000,  0.00000,  0.0000]
d = [0.089159,  0.00000,  0.00000,  0.10915,  0.09465,  0.0823]
alpha = [ 1.570796327, 0, 0, 1.570796327, -1.570796327, 0 ]
q_home_offset = [0, -1.570796327, 0, -1.570796327, 0, 0]
joint_direction = [-1, -1, 1, 1, 1, 1]

DH for UR10:
a = [0.000, -0.612, -0.5723, 0.000000, 0.0000, 0.0000]
d = [0.1273,  0.000,  0.0000, 0.163941, 0.1157, 0.0922]
alpha = [ 1.570796327, 0, 0, 1.570796327, -1.570796327, 0 ]
q_home_offset = [0, -1.570796327, 0, -1.570796327, 0, 0]
joint_direction = [1, 1, -1, 1, 1, 1]

Mass for UR5:
mass = [3.7000, 8.3930, 2.2750, 1.2190, 1.2190, 0.1879]
center_of_mass = [ [0, -0.02561, 0.00193], [0.2125, 0, 0.11336], [0.11993, 0.0, 0.0265], [0, -0.0018, 0.01634], [0, 0.0018,0.01634], [0, 0, -0.001159] ]

Mass for UR10:
mass = [7.778, 12.930, 3.87, 1.96, 1.96, 0.202]
center_of_mass = [ [0.00008, -0.037, 0.00244], [0.38757, 0.00001, 0.15061], [0.1984, -0.00012, 0.06112], [-0.00021, -0.00112, 0.02269], [-0.00021, 0.00112, 0.002269], [-0.00149, 0, -0.001156] ]

-->

  <property name="pi" value="3.14159265" />

<!-- Inertia parameters -->
  <property name="base_mass" value="4.0" /> <!-- Invented number, only matters for simulator -->
  <property name="shoulder_mass" value="7.778" />
  <property name="upper_arm_mass" value="12.930" />
  <property name="forearm_mass" value="3.87" />
  <property name="wrist_1_mass" value="1.96" />
  <property name="wrist_2_mass" value="1.96" />
  <property name="wrist_3_mass" value="0.202" />

  <!-- TODO -->
  <property name="shoulder_cog" value="0.0 0.00193 -0.02561" />
  <property name="upper_arm_cog" value="0.0 -0.024201 0.2125" />   <!-- 0.11336 - 0.089159 =  -->
  <property name="forearm_cog" value="0.0 0.0265 0.11993" />       <!-- 0.119 is not half of 0.39225, is this really correct? -->
  <property name="wrist_1_cog" value="0.0 0.110949 0.01634" />     <!-- 0.0018 + 0.10915 = 0.110949 -->
  <property name="wrist_2_cog" value="0.0 0.0018 0.11099" />       <!-- 0.01634 + 0.09465 = 0.11099-->
  <property name="wrist_3_cog" value="0.0 0.001159 0.0" />
  <!-- TODO -->

<!-- Kinematic model -->
  <property name="shoulder_height" value="0.1273" />  
  <property name="shoulder_offset" value="0.13585" />  <!-- shoulder_offset - elbow_offset + wrist_1_length = 0.10915 -->
  <property name="upper_arm_length" value="0.612" />
  <property name="elbow_offset" value="0.1197" />       <!-- CAD measured TODO -->
  <property name="forearm_length" value="0.5723" />
  <property name="wrist_1_length" value="0.093" />     <!-- CAD measured TODO -->
  <property name="wrist_2_length" value="0.1157" />   <!-- In CAD this distance is 0.930, but in the spec it is 0.09465 -->
  <property name="wrist_3_length" value="0.0922" />

  <property name="shoulder_radius" value="0.075" />   <!-- manually measured -->
  <property name="upper_arm_radius" value="0.054" />  <!-- manually measured -->
  <property name="elbow_radius" value="0.060" />      <!-- manually measured -->
  <property name="forearm_radius" value="0.040" />    <!-- manually measured -->
  <property name="wrist_radius" value="0.045" />      <!-- manually measured -->

<!-- Collision model -->
  <property name="base_collision_length" value="0.215" />      <!-- manually measured -->
  <property name="shoulder_collision_length" value="0.177" />  <!-- manually measured -->
  <property name="shoulder_collision_offset" value="0.035" />  <!-- manually measured -->
  <property name="elbow_collision_length" value="0.200" />     <!-- manually measured -->
  <property name="elbow_collision_offset" value="0.035" />     <!-- manually measured -->



<xacro:macro name="ur10_robot" params="prefix">

  <link name="${prefix}base_link" >
    <visual>
      <geometry>
        <mesh filename="package://ur10_description/meshes/Base.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="${pi / 2.0} 0.0 0.0" />
    </visual>
    <inertial>
      <mass value="${base_mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="${prefix}shoulder_pan_joint" type="revolute">
    <parent link="${prefix}base_link" />
    <child link = "${prefix}shoulder_link" />
    <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 0.0 1.0" />
    <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="10.0" velocity="${pi}"/>
    <dynamics damping="10" friction="0.1"/>
  </joint>
  
  <link name="${prefix}shoulder_link">
    <visual>
      <geometry>
        <mesh filename="package://ur10_description/meshes/Shoulder.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0.0 0.0 -0.127" rpy="${pi / 2.0} 0.0 0.0" />
    </visual>
    <collision>
      <geometry>
        <cylinder length="${base_collision_length}" radius="${shoulder_radius}"/>
      </geometry>
      <origin xyz="0.0 0.0 ${-shoulder_height + (base_collision_length/2.0)}" rpy="0.0 0.0 0.0" />
    </collision>
    <inertial>
      <mass value="${shoulder_mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      <origin xyz="${shoulder_cog}" rpy="0.0 0.0 0.0" />
    </inertial>
  </link>

  <joint name="${prefix}shoulder_lift_joint" type="revolute">
    <parent link="${prefix}shoulder_link" />
    <child link = "${prefix}upper_arm_link" />
    <origin xyz="0.0 ${shoulder_offset} 0.0" rpy="0.0 ${pi / 2.0} 0.0" />    
    <axis xyz="0.0 1.0 0.0" />
    <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="10.0" velocity="${pi}"/>
    <dynamics damping="10" friction="0.1"/>
  </joint>

  <joint name="${prefix}upper_shoulder_joint" type="fixed">
    <parent link="${prefix}upper_arm_link" />
    <child link = "${prefix}upper_shoulder_link" />
    <origin xyz="0.0 -0.053 0.0" rpy="${-pi/2.0} 0.0 0.0" />    
  </joint>

  <link name="${prefix}upper_shoulder_link">
    <collision>
      <geometry>
        <cylinder length="${base_collision_length}" radius="${shoulder_radius}"/>
      </geometry>
      <origin xyz="0.0 0.0 ${shoulder_height}" rpy="0.0 0.0 0.0" />
    </collision>
    <inertial>
      <mass value="0" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
    </inertial>
  </link>

  <link name="${prefix}upper_arm_link">
    <visual>
      <geometry>
        <mesh filename="package://ur10_description/meshes/UpperArm.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0.0 -0.136 -0.127" rpy="${pi / 2.0} -${0*pi / 2.0} 0.0" />
    </visual>
    <collision>
      <geometry>
        <cylinder length="${upper_arm_length}" radius="${upper_arm_radius}"/>
      </geometry>
      <origin xyz="0.0 0.0 ${upper_arm_length/2.0}" rpy="0.0 0.0 0.0" />
    </collision>
    <inertial>
      <mass value="${upper_arm_mass}" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
      <origin xyz="${upper_arm_cog}" rpy="0.0 0.0 0.0" />
    </inertial>
  </link>

  <joint name="${prefix}elbow_joint" type="revolute">
    <parent link="${prefix}upper_arm_link" />
    <child link = "${prefix}forearm_link" />
    <origin xyz="0.0 ${-elbow_offset} ${upper_arm_length}" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 1.0 0.0" />
    <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="10.0" velocity="${pi}"/>
    <dynamics damping="10" friction="0.1"/>
  </joint>

  <link name="${prefix}forearm_link">
    <visual>
      <geometry>
        <mesh filename="package://ur10_description/meshes/Forearm.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0.0 -0.016 -0.739" rpy="${pi / 2.0} 0.0 0.0" />
    </visual>
    <collision>
      <geometry>
        <cylinder length="${forearm_length}" radius="${forearm_radius}"/>
      </geometry>
      <origin xyz="0.0 0.0 ${forearm_length/2.0}" rpy="0.0 0.0 0.0" />
    </collision>
    <inertial>
      <mass value="${forearm_mass}" />
      <origin xyz="${forearm_cog}" rpy="0.0 0.0 0.0" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="${prefix}wrist_1_joint" type="revolute">
    <parent link="${prefix}forearm_link" />
    <child link = "${prefix}wrist_1_link" />
    <origin xyz="0.0 0.0 ${forearm_length}" rpy="0.0 ${pi / 2.0} 0.0" />
    <axis xyz="0.0 1.0 0.0" />
    <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="10.0" velocity="${pi}"/>
    <dynamics damping="10" friction="0.1"/>
  </joint>

  <link name="${prefix}wrist_1_link">
    <visual>
      <geometry>
        <mesh filename="package://ur10_description/meshes/Wrist1.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0.0 -0.016 -1.312" rpy="${pi / 2.0} 0.0 0.0" />
    </visual>
    <collision>
      <geometry>
        <cylinder length="${1.6*wrist_1_length}" radius="${wrist_radius}"/>
      </geometry>
      <origin xyz="0.0 ${0.25*wrist_1_length} 0.0" rpy="${-pi/2.0} 0.0 0.0" />
    </collision>
    <inertial>
      <mass value="${wrist_1_mass}" />
      <origin xyz="${wrist_1_cog}" rpy="0.0 0.0 0.0" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="${prefix}wrist_2_joint" type="revolute">
    <parent link="${prefix}wrist_1_link" />
    <child link = "${prefix}wrist_2_link" />
    <origin xyz="0.0 ${wrist_1_length} 0.0" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 0.0 1.0" />
    <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="10.0" velocity="${pi}"/>
    <dynamics damping="10" friction="0.1"/>
  </joint>

  <link name="${prefix}wrist_2_link">
    <visual>
      <geometry>
        <mesh filename="package://ur10_description/meshes/Wrist2.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0.0 -0.109 -1.312" rpy="${pi / 2.0} 0.0 0.0" />
    </visual>
    <collision>
      <geometry>
        <cylinder length="${1.6*wrist_2_length}" radius="${wrist_radius}"/>
      </geometry>
      <origin xyz="0.0 0.0 ${0.25*wrist_2_length}" rpy="0.0 0.0 0.0" />
    </collision>
    <inertial>
      <mass value="${wrist_2_mass}" />
      <origin xyz="${wrist_2_cog}" rpy="0.0 0.0 0.0" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <joint name="${prefix}wrist_3_joint" type="revolute">
    <parent link="${prefix}wrist_2_link" />
    <child link = "${prefix}wrist_3_link" />
    <origin xyz="0.0 0.0 ${wrist_2_length}" rpy="0.0 0.0 0.0" />
    <axis xyz="0.0 1.0 0.0" />
    <limit lower="${-2.0 * pi}" upper="${2.0 * pi}" effort="10.0" velocity="${pi}"/>
    <dynamics damping="10" friction="0.1"/>
  </joint>

  <link name="${prefix}wrist_3_link">
    <visual>
      <geometry>
        <mesh filename="package://ur10_description/meshes/Wrist3.dae" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0.0 -0.109 -1.427" rpy="${pi / 2.0} 0.0 0.0" />
    </visual>
    <collision>
      <geometry>
        <cylinder length="${1.65*wrist_3_length}" radius="${wrist_radius}"/>
      </geometry>
      <origin xyz="0.0 ${0.15 * wrist_3_length} 0.0" rpy="${-pi/2.0} 0.0 0.0" />
    </collision>
    <inertial>
      <mass value="${wrist_3_mass}" />
      <origin xyz="${wrist_3_cog}" rpy="0.0 0.0 0.0" />
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>
  
  <joint name="${prefix}ee_fixed_joint" type="fixed">
    <parent link="${prefix}wrist_3_link" />
    <child link = "${prefix}ee_link" />
    <origin xyz="0.0 ${wrist_3_length} 0.0" rpy="0.0 0.0 ${pi/2.0}" />    
  </joint>

  <link name="${prefix}ee_link" />
  


  <!-- Extra links for collision model -->
  <!-- Somehow don't work with gazebo TODO: fix this
  <joint name="${prefix}shoulder_collision_joint" type="fixed">
    <parent link="${prefix}upper_arm_link" />
    <child link = "${prefix}shoulder_collision_link" />
  </joint>
  <link name="${prefix}shoulder_collision_link">
    <collision>
      <geometry>
        <cylinder length="${shoulder_collision_length}" radius="${shoulder_radius}"/>
      </geometry>
      <origin xyz="0.0 ${-shoulder_collision_offset} 0.0" rpy="${-pi / 2.0} 0.0 0.0" />
    </collision>
  </link>

  <joint name="${prefix}elbow_collision_joint" type="fixed">
    <parent link="${prefix}upper_arm_link" />
    <child link = "${prefix}elbow_collision_link" />
  </joint>
  <link name="${prefix}elbow_collision_link">
    <collision>
      <geometry>
        <cylinder length="${elbow_collision_length}" radius="${elbow_radius}"/>
      </geometry>
      <origin xyz="0.0 ${-elbow_collision_offset} ${upper_arm_length}" rpy="${pi / 2.0} 0.0 0.0" />
    </collision>
  </link>
  -->

  <xacro:ur_arm_transmission name="${prefix}" />

  <gazebo reference="universal_robot">
    <material>Gazebo/Blue</material>
  </gazebo>


</xacro:macro>
</robot>
