# Goal Definition
std_msgs/Header header
geometry_msgs/Pose2D desired_pose
string which_arm
string controller_name
string proxy_name
string behavior_primitive
---
# Result Definition
std_msgs/Header header
geometry_msgs/Pose2D x
geometry_msgs/Pose2D x_error
bool aborted
---
# Feedback Definition
std_msgs/Header header
geometry_msgs/Pose2D x # Object pose
geometry_msgs/Pose2D x_dot # Object velocity
geometry_msgs/Pose2D init_x # Object pose
float64 z
bool no_detection
string controller_name
string proxy_name
string behavior_primitive
float64[] shape_descriptor